const Map<String,String> fr ={
  'Out to Deliver':'Sortie en livraison',
  'Delivered':'Livrés',
  'Failed Attempt':'Tentatives\n échouées',
  'Home':'Accueil',
  'History': 'Historique',
  'Wallet':'Portefeuille',
  'Profile':'Profil',
  'Please Create a Mission':'Veuillez créer une mission',
  'to start!':' Pour commencer!',
  'Cancel':'Annuler',
  'Submit' :'Soumettre',
  'Today':'Aujourd\'hui',
  'Week' : 'Semaine',
  'Month': 'Mois',
  'Year':'Année',
  'All Shipments':'tous les Colis',
  'Not Delivered' : 'Non livrés',
  'Balance':'Le Solde',
  'Collected Amount':'Montant collecté',
  'Delivery Fee':'Frais de livraison',
  'My Informations':'Mes informations',
   'Name,Email':'Nom,E-mail',
  'Call Center':'Centre d\'appel',
  'Helpdesk,Reports':'Service d\'assistance, rapports',
  'Billing Details':'Détails de la facturation',
  'Benefits,Money':'Revenus, Argent',
  'Legal informations':'Informations légales',
  'Terms & Conditions,Privacy policy':'Conditions générales,Politique de confidentialité',
  'Log out':'Se déconnecter',
  'Email: ':'E-mail: ',
  'Name: ':'Nom: ',
  'Phone Number: ':'Numéro de téléphone: ',
  'City: ':'Ville: ',
  'Not Declared':'Non déclaré',
  'Order Id:':'Colis Id: ',
  'Receiver address:': 'Adresse du destinataire : ',
  'Amount to be collected:':'Montant à collecter: ',
  'From: ':'De: ',
  'To: ':'À: ',
  'Failed Attempt Shipments':'Échec de tentative d\'expédition',
  ' List is Empty !':'La liste est vide !',
  'Restore Shipments ':'Restaurer les Commandes',
  'DONE':'Valider',
  'List is Empty':'La liste est vide ',
  'Create a mission to start!':'Créez une mission pour commencer !',
  'Assigned Shipment':'Commandes Assignées',
  'Create Mission':'Créer une mission',
  'Edit mission':'Modifier la mission',
  'Login':'Connexion',
  'Password':'Mot de passe',
  'LOGIN':'Se Connecter',
  'Order':'Colis',
  'Order Detail':'Détails du Colis',
  'Call Client':'Appeler le client',
  'Shipping Cost:':'Frais de la Livraison:',
  'Package Cost:': 'Coût du Colis',
   'Location':'la localisation',
  'Customer':'le client',
  'Name:':'Nom:',
  'Mobile Number:':'Numéro de portable:',
  'Canceled':'Annuler',
  'Error", "invalid shipment please try again!':'Erreur", "Colis non valide, veuillez réessayer !',
  'Are you sure that this shipment is Delivered ?':'Êtes-vous sûr que cet Colis est Livré ?',
  'Confirm':'Confirmer',
  '  Deliver  ':'  Livrer  ',
  'Validate':'Valider',
   'the List is already Empty!':'la liste est déjà vide !',
  'List is Empty Please Scan!':'La liste est vide, veuillez scanner le code !',
  'Error':'Erreur',
  'Please Scan the Courier':'Veuillez scanner le colis',
  'Are you sure to Validate this List ?':'Êtes-vous sûr de valider cette liste ?',
  'Delete':'Supprimer',
  'Are you sure to Delete this List ?':'Êtes-vous sûr de supprimer cette liste ?',
  'No':'Non',
  'Yes':'Oui',
  'All Shipments are Canceled':'Tous les Colis sont annulés',
  'Hidden':'Caché',
  'Failed Attempts Shipments':'Les Tentatives échouées',
  'Delivered Shipment Details':'Details du Colis',
  'Reasons':'Les Raisons',
  'Select the key of reason':'Sélectionnez la clé',
  'Available':'Disponible',
  'Tracking Code:':'Code du Colis:',
  'Status:':'Statut:',
  'Collected Amount:':'Montant collecté :',
  'DA ':'DA ',
   'Are you sure to add this shipment to your mission ?':'Êtes-vous sûr d\'ajouter ce colis à votre mission ?',
  'Add Shipment':'Ajouter un Colis',
  'Sender Number:':'Numéro d\'expéditeur :',
  'Delivery fee prices':'Tarifs des frais de livraison',
  'Area':'Commune',
  'Return Fees':'Frais de retour',
  'Delivery Fees':'Frais de livraison',
  'Default Fees: ':'Frais par défaut : ',
  'All':'Toute',
  'Add another reason here...':'Ajoutez une autre raison ici...',
  'Alert':'Alerte',
  'Reason of Alert:':'Raison de l\'alerte :'









};