
const Map<String, String> ar = {
  'Out to Deliver':'خارج للتسليم',
  'Delivered':'تم التوصيل',
  'Failed Attempt':'محاولات فاشلة',
  'Home':'الرئيسية',
  'History': 'سجل الطلبيات',
  'Wallet':'محفظة النقود',
  'Profile':'الملف الشخصي',
  'Please Create a Mission':'الرجاء إنشاء مهمة',
  'to start!':' للبدأ!',
  'Cancel':'إلغاء',
  'Submit' :'حفظ',
  'Today':'اليوم',
  'Week' : 'أسبوع',
  'Month': 'شهر',
  'Year':'عام',
  'All Shipments':'جميع الطلبيات',
  'Not Delivered' : 'غير موزعة',
  'Balance':'الرصيد',
  'Collected Amount':'المبلغ المحصل',
  'Delivery Fee':'رسوم التوصيل',
  'My Informations':'معلوماتي',
  'Name,Email':'الاسم والبريد الإلكتروني',
  'Call Center':'مركز الاتصال',
  'Helpdesk,Reports':'مكتب المساعدة والتقارير',
  'Billing Details':'تفاصيل الفاتورة',
  'Benefits,Money':'الفوائد والمال',
  'Legal informations':'المعلومات القانونية',
  'Terms & Conditions,Privacy policy':'الشروط والأحكام وسياسة الخصوصية',
  'Log out':'تسجيل خروج',
  'Email: ':'بريد الالكتروني: ',
  'Name: ':'الاسم: ',
  'Phone Number: ':'رقم الهاتف: ',
  'City: ':'المدينة: ',
  'Not Declared':'غير معلن',
  'Order Id:':'رقم الطرد: ',
  'Receiver address:': 'عنوان المستلم: ',
  'Amount to be collected:':'المبلغ المطلوب تحصيله:',
  'From: ':'من:  ',
  'To: ':'الى:  ',
  'DA ':'  دج',
  'Failed Attempt Shipments':'محاولة الطلبيات الفاشلة',
  ' List is Empty !':'القائمة فارغة !',
  'Restore Shipments ':'استعادة الطلبات',
  'DONE':'تأكيد',
  'List is Empty':'القائمة فارغة !',
  'Create a mission to start!':'أنشئ مهمة لتبدأ!',
  'Assigned Shipment':'الطلبيات المعينة بالموزع',
  'Create Mission':'أنشئ مهمة',
  'Edit mission':'تعديل في المهمة',
  'Login':'تسجيل الدخول',
  'Password':'كلمة المرور',
  'LOGIN':'تسجيل الدخول',
  'Order':'الطلبية',
  'Order Detail':'تفاصيل الطلبية',
  'Call Client':'اتصل بالزبون',
  'Shipping Cost:':'تكاليف التوزيع:',
  'Package Cost:': 'تكلفة الطرد',
  'Location':'تحديد الموقع',
  'Customer':'الزبون',
  'Name:':'الاسم:',
  'Mobile Number:':'رقم الهاتف المحمول:',
  'Canceled':'إلغاء',
  'Error", "invalid shipment please try again!':'Erreur", "Colis non valide, veuillez réessayer !',
  'Are you sure that this shipment is Delivered ?':'هل أنت متأكد من تسليم هذه الطلبية؟',
  'Confirm':'تأكيد',
  '  Deliver  ':'تسليم الطلبية',
  'Validate':'تأكيد',
  'the List is already Empty!':'القائمة فارغة بالفعل!',
  'List is Empty Please Scan!':'القائمة فارغة الرجاء المسح الضوئي للطلبية!',
  'Error':'خطأ',
  'Please Scan the Courier':'يرجى مسح الحزمة ضوئيًة للطلبية',
  'Are you sure to Validate this List ?':'هل أنت متأكد من التحقق من صحة هذه القائمة؟',
  'Delete':'حذف',
  'Are you sure to Delete this List ?':'هل أنت متأكد أنك تريد حذف هذه القائمة؟',
  'No':'لا',
  'Yes':'نعم',
  'All Shipments are Canceled':'تم إلغاء جميع الطرود',
  'Hidden':'مخفي',
  'Failed Attempts Shipments':'محاولات فاشلة',
  'Delivered Shipment Details':'تفاصيل الطلبية',
  'Reasons':'الاسباب',
  'Select the key of reason':'حدد من اين السبب',
  'Available':'متوفرة',
  'Tracking Code:':'كود الطلبية:',
  'Status:':'الحالة:',
  'Collected Amount:':'المبلغ الذي تم تجميعه:',
  'Are you sure to add this shipment to your mission ?':'هل أنت متأكد من إضافة هذه الطلبية إلى مهمتك؟',
  'Add Shipment':'إضافة طرد',
  'Sender Number:':'رقم المرسل:',
  'Delivery fee prices':'أسعار رسوم التوصيل',
  'Area':'البلدية',
  'Return Fees':'رسوم الإرجاع',
  'Delivery Fees':'تكاليف التوصيل',
  'Default Fees: ':'تكاليف التوصيل',
  'All':'الكل',
  'Add another reason here...':'أضف سببًا آخر هنا ...',
  'Alert':'إنذار',
  'Reason of Alert:':'سبب الانذار:  '


};